before:
  hooks:
    - go mod download
builds:
  - id: kpexec
    main: ./cmd/kpexec/main.go
    binary: kpexec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/ssup2/kpexec/pkg/cmd/kpexec.version={{ .Tag }}
  - id: kubectl-pexec
    main: ./cmd/kpexec/main.go
    binary: kubectl-pexec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/ssup2/kpexec/pkg/cmd/kpexec.version={{ .Tag }}
      - -X github.com/ssup2/kpexec/pkg/cmd/kpexec.build=kubectlPlugin
archives:
  - id: kpexec
    builds:
      - kpexec
    name_template: "kpexec_v{{ .Version }}_{{ title .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  - id: kubectl-pexec
    builds:
      - kubectl-pexec
    name_template: "kubectl_pexec_v{{ .Version }}_{{ title .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
brews:
  - name: kpexec
    ids:
      - kpexec
    repository:
      owner: ssup2
      name: homebrew-tap
