apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pexec
spec:
  homepage: https://github.com/ssup2/kpexec
  shortDescription: Execute process with privileges in a pod
  description: |
    pexec is a kubernetes cli that runs commands in a container with high
    privileges. It runs a highly privileged container on the same node as
    the target container and joins into the namespaces of the target container
    (IPC, UTS, PID, net, mount). This is useful for debugging where you often
    need to execute commands with high privileges. Also, pexec has a tools
    mode, which adds useful debugging tools into the debugged container. The
    tools mode is useful when there necessary debugging tools are missing in the
    target container.

    In contrast, kubectl-exec runs the command with the same privileges as the
    container. For example, if a container does not have network privileges,
    the command executed by kubectl-exec also has no network privileges.
    This makes debugging the pod difficult. If you use pexec instead
    of kubectl-exec, you can easily get high privileges for debugging.
  caveats: |
    pexec requires the privileges to run privileged pods with hostPID.
  version: "{{ .TagName }}"
  platforms:
  - bin: kubectl-pexec
    {{addURIAndSha "https://github.com/ssup2/kpexec/releases/download/{{ .TagName }}/kubectl_pexec_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - bin: kubectl-pexec
    {{addURIAndSha "https://github.com/ssup2/kpexec/releases/download/{{ .TagName }}/kubectl_pexec_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: arm64
  - bin: kubectl-pexec
    {{addURIAndSha "https://github.com/ssup2/kpexec/releases/download/{{ .TagName }}/kubectl_pexec_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - bin: kubectl-pexec
    {{addURIAndSha "https://github.com/ssup2/kpexec/releases/download/{{ .TagName }}/kubectl_pexec_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - bin: kubectl-pexec.exe
    {{addURIAndSha "https://github.com/ssup2/kpexec/releases/download/{{ .TagName }}/kubectl_pexec_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: windows
        arch: amd64
  - bin: kubectl-pexec.exe
    {{addURIAndSha "https://github.com/ssup2/kpexec/releases/download/{{ .TagName }}/kubectl_pexec_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: windows
        arch: arm64
