# syntax=docker/dockerfile:latest
# Build cnsenter
FROM --platform=${TARGETPLATFORM} golang:1.20.8 as builder

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG VERSION

WORKDIR /workspace

COPY . .

RUN CGO_ENABLED=0 GO111MODULE=on go build -a -ldflags="-X 'github.com/ssup2/kpexec/pkg/cmd/cnsenter.version=${VERSION}'" -o cnsenter cmd/cnsenter/main.go

# Download crictl
FROM alpine:3 as downloader

ARG TARGETPLATFORM

ENV CRICTL_VERSION v1.24.1

RUN [ "$TARGETPLATFORM" == "linux/arm64" ] && export ARCHITECTURE=arm || export ARCHITECTURE=amd64

RUN curl -LsSf "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-${ARCHITECTURE}.tar.gz" | tar xzvf - -C /usr/local/bin

# Build image
FROM --platform=${TARGETPLATFORM} alpine:3

COPY --from=builder --chmod=755 --chown=root /workspace/cnsenter /usr/local/bin/cnsenter
COPY --from=downloader --chmod=755 --chown=root /usr/local/bin/crictl /usr/local/bin/crictl
COPY --chmod=755 --chown=root scripts/remount-proc-exec /usr/bin/remount-proc-exec

RUN apk add \
	apache2-utils \
	bash \
	bind-tools \
	conntrack-tools \
	curl \
	dhcping \
	drill \
	ethtool \
	htop \
	iftop \
	iperf \
	iproute2 \
	ipset \
	iptables \
	iputils \
	jq \
	nano \
	net-tools \
	net-snmp-tools \
	nftables \
	nmap \
	nmap-ncat \
	nmap-nping \
	openssl \
	socat \
	tcpdump \
	tcptraceroute \
	tshark \
	vim \
	wrk

CMD ["cnsenter"]
HEALTHCHECK NONE
