# Build cnsenter
FROM golang:1.16 as builder
WORKDIR /workspace

ARG VERSION
COPY . .
RUN CGO_ENABLED=0 GO111MODULE=on go build -a -ldflags="-X 'github.com/ssup2/kpexec/pkg/cmd/cnsenter.version=${VERSION}'" -o cnsenter cmd/cnsenter/main.go

# Download crictl
FROM alpine:3.13.1 as downloader
ENV CRICTL_VERSION v1.24.1
RUN wget https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz
RUN tar zxvf crictl-${CRICTL_VERSION}-linux-amd64.tar.gz -C /usr/local/bin

# Build image
# Reference - https://github.com/nicolaka/netshoot
FROM alpine:3.13.1
COPY --from=builder /workspace/cnsenter /usr/local/bin/cnsenter
COPY --from=downloader /usr/local/bin/crictl /usr/local/bin/crictl
COPY scripts/remount-proc-exec /usr/bin/remount-proc-exec
RUN apk add \
	apache2-utils \
	bash \
	bind-tools \
	conntrack-tools \
	curl \
	dhcping \
	drill \
	ethtool \
	htop \
	iftop \
	iperf \
	iproute2 \
	ipset \
	iptables \
	iputils \
	jq \
	nano \
	net-tools \
	net-snmp-tools \
	nftables \
	nmap \
	nmap-ncat \
	nmap-nping \
	openssl \
	socat \
	tcpdump \
	tcptraceroute \
	tshark \
	vim \ 
	wrk 

CMD ["cnsenter"]
